name: azure-vm-start
on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start VM
        run: |
          az vm start \
            --name "${{ secrets.AZURE_VM_NAME }}" \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}"