name: build-and-publish-docker-image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag de la imagen (ej. v1.2.3)"
        required: false
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: t
        run: |
          echo "image=ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.t.outputs.image }}:${{ steps.t.outputs.tag }}
            ${{ steps.t.outputs.image }}:${{ github.sha }}