name: ghcr-publish-docker-image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag de la imagen (ej. v1.2.3)"
        required: false
        default: latest

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags
        id: tags
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}"
          TAG="${{ github.event.inputs.tag || 'latest' }}"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG"     >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: |
            ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
            ${{ steps.tags.outputs.image }}:${{ github.sha }}
          secrets: | 
            gpr_user=${{ github.actor }}
            gpr_key=${{ secrets.GITHUB_TOKEN }}